# permissions for end users to edit hardwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardware-editor-role
rules:
- apiGroups:
  - tink.tinkerbell.org
  resources:
  - hardwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tink.tinkerbell.org
  resources:
  - hardwares/status
  verbs:
  - get
