# permissions for end users to view hardwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardware-viewer-role
rules:
- apiGroups:
  - tink.tinkerbell.org
  resources:
  - hardwares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tink.tinkerbell.org
  resources:
  - hardwares/status
  verbs:
  - get
