apiVersion: tink.tinkerbell.org/v1
kind: Hardware
metadata:
  name: hardware-sample
spec:
  # Add fields here
  data:
    id: 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94
    metadata:
      bonding_mode: 5
      custom:
        preinstalled_operating_system_version: {}
        private_subnets: []
      facility:
        facility_code: ewr1
        plan_slug: c2.medium.x86
        plan_version_slug: ''
      instance:
        crypted_root_password: redacted
        operating_system_version:
          distro: ubuntu
          os_slug: ubuntu_18_04
          version: '18.04'
        storage:
          disks:
          - device: "/dev/sda"
            partitions:
            - label: BIOS
              number: 1
              size: 4096
            - label: SWAP
              number: 2
              size: 3993600
            - label: ROOT
              number: 3
              size: 0
            wipe_table: true
          filesystems:
          - mount:
              create:
                options:
                - "-L"
                - ROOT
              device: "/dev/sda3"
              format: ext4
              point: "/"
          - mount:
              create:
                options:
                - "-L"
                - SWAP
              device: "/dev/sda2"
              format: swap
              point: none
      manufacturer:
        id: ''
        slug: ''
      state: ''
    network:
      interfaces:
      - dhcp:
          arch: x86_64
          hostname: server001
          ip:
            address: 192.168.1.5
            gateway: 192.168.1.1
            netmask: 255.255.255.248
          lease_time: 86400
          mac: 00:00:00:00:00:00
          name_servers: []
          time_servers: []
          uefi: false
        netboot:
          allow_pxe: true
          allow_workflow: true
          ipxe:
            contents: "#!ipxe"
            url: http://url/menu.ipxe
          osie:
            base_url: ''
            initrd: ''
            kernel: vmlinuz-x86_64

